---
meta:
    description:
        Creates the IAM roles necessary for the TAPI to work
    dependencies:
        - streams
    parameters:
        streams:
            description: The name of the Kinesis streams for the various event types
            value:
                visit:
                    ref:
                        parser: layer
                        parameters:
                            layer_name: streams
                            resource_name: VisitStream
                search:
                    ref:
                        parser: layer
                        parameters:
                            layer_name: streams
                            resource_name: SearchStream
                lead:
                    ref:
                        parser: layer
                        parameters:
                            layer_name: streams
                            resource_name: LeadStream
                booking:
                    ref:
                        parser: layer
                        parameters:
                            layer_name: streams
                            resource_name: BookingStream
