---
meta:
    description:
        Creates the IAM roles necessary for the TAPI to work
    dependencies:
        - streams
    parameters:
        streams:
            description: The name of the Kinesis streams for the various event types
            value:
                visit: 
                    ref: streams/VisitStream
                search:
                    ref: streams/SearchStream
                lead:
                    ref: streams/LeadStream
                booking:
                    ref: streams/BookingStream
