---
meta:
    description:
        Creates the IAM roles necessary for the TAPI to work
    dependencies:
        - streams
    parameters:
        streams:
            description: The name of the Kinesis streams for the various event types
            value:
                visit: 
                    ref: $layer[streams/VisitStream]
                search:
                    ref: $layer[streams/SearchStream]
                lead:
                    ref: $layer[streams/LeadStream]
                booking:
                    ref: $layer[streams/BookingStream]
