---
meta:
    description:
        Templated lambda function that displays info about the environment
    parameters:
        dummy_function:
            description: The code of the dummy Lambda function
            value:
                ref: 
                    parser: lambda
                    parameters:
                        path: dummy_function.py.j2
