---
meta:
    description:
        Dummy Lambda function that does nothing
    dependencies:
        - lambda-role
    parameters:
        dummy_function:
            description: The code of the dummy Lambda function
            value:
                ref: 
                    parser: file
                    parameters:
                        path: dummy_function.zip
        role:
            description: The role to associate to the dummy Lambda function
            value:
                ref: 
                    parser: output
                    parameters:
                        layer_name: lambda-role
                        output_name: DummyRoleArn
