---
example-environment:
    description:
        Adapted from the example mega-stack in the cumulus project
    region: us-west-2
    layers:
        - {layer: vpc, some_meta_parameter: 1, vpc_cidr: 10.0.0.4}
        - {layer: instance}
