---
meta:
    description:
        A templated lambda function with install requirements
    parameters:
        dummy_function:
            description: The code of the templated Lambda function
            value:
                ref: 
                    parser: lambda
                    parameters:
                        path: dummy_function
